[package]
name = "lexicc"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.47.0"
aws-sdk-polly = "0.17.0"
dirs = "4.0.0"
regex = "1.6.0"
rodio = "0.15.0"
sysinfo = "0.25.2"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
